### ISSUE TITLE
Update Matters Served tag styling

### ISSUE THREAD

**Issue by lucychen11** [Exygy/ftrc#1]
Referring to the tags below:
![image](https://user-images.githubusercontent.com/13025486/51625152-50057f80-1ef1-11e9-9185-d95e2ec086e9.png)

Update styling for tags to the one displayed in this design: https://projects.invisionapp.com/d/main#/console/15922115/334787937/preview

**Comment by exygy-dev** [comment]
@jaredcwhite Also-- remove the hover tool-tip on Matters Served-- we've decided that we're not using that behavior anymore (see below)
![image](https://user-images.githubusercontent.com/13025486/51725442-0ca53100-2017-11e9-8553-716efbdb32c5.png)

**Comment by jaredcwhite** [comment]
Fixed and pushed
