### ISSUE TITLE
error handling: matches location but no court data

### ISSUE THREAD

**Issue by cydharrell** [Exygy/ftrc#10]
(this is unlikely to happen once full data is in the spreadsheet, but we should have a backstop for it.) Right now, entering a location that is not in the production dataset yet (as of 1/11, "napa" is a good example), returns "No court found. There are 0 Courthouses Locations in this jurisdiction." 

We should add a "try another search" box and ideally, we should change the language to "we don't have courthouse data for this location".

**Comment by jaredcwhite** [comment]
Fixed and pushed
