### ISSUE TITLE
courthouse address formatting

### ISSUE THREAD

**Issue by cydharrell** [Exygy/ftrc#15]
<img width="835" alt="screen shot 2019-01-17 at 10 20 53 am" src="https://user-images.githubusercontent.com/5133498/51339588-a67e4400-1a41-11e9-980e-7983afe2a7f5.png">

Courthouse addresses aren't properly picking up the break between the street address line and the City/State line. (Can't tell if this is only a problem when the street address wraps to a second line.) This is confusing & hard to read. Addresses are pre-entered with a return in the Google sheet - is it possible to pick that up?

**Comment by jaredcwhite** [comment]
Fixed and pushed

**Comment by cydharrell** [comment]
Jared figured out this was a data problem & I've fixed it
