### ISSUE TITLE
links w/in Matter Distribution Summary or Parking

### ISSUE THREAD

**Issue by cydharrell** [Exygy/ftrc#17]
We have a few cases where courts have provided information that includes a link as part of either their Matter Distribution Summary (displayed at top under the "which court this is") or as part of Parking information. Right now, these are being shown as plain text & aren't clickable. One solution is to simply make them clickable links as is; I'm open to others.

Test case: see Orange Superior Court page - use 92701 in the search.

**Comment by cydharrell** [comment]
noting that Ventura County also has a link under Assistance/resource center hours - need to check for others

**Comment by cydharrell** [comment]
note, if this is something where writing HTML links w/in the Google Sheet will work/is needed, that's fine

**Comment by jaredcwhite** [comment]
Fixed and pushed.
