### ISSUE TITLE
Add popup for 'when not to go to the closest court'

### ISSUE THREAD

**Issue by lucychen11** [Exygy/ftrc#2]
https://docs.google.com/document/d/1UbmqSHlGH8AB-b-4ekvWGXKsuOqbnAM2do7c0khcnSc/edit

**Comment by exygy-dev** [comment]
Add styling for content in CourtExceptionsModal.

The following lines of text should have <h2> styling:
- Responding to an existing case (find information on papers you received), file at the court where the:
- Cases about car accidents, file at the court where the:
- Suing a business (something you purchased), file at the court where the:
- Suing for non-payment (something you sold), file at the court where the: (note: this should be pulled out of the <ul>)
- Cases involving minors, file at court where the:
- For the following cases involving minors, you can usually file at the court where the minor lives:

**Comment by cydharrell** [comment]
New text! https://docs.google.com/document/d/1ahF6LSG0NvLYyqtthfR31DZ483S_dey1Rl8HNPFaMl4/edit (may still have minor changes - to one or two bullets.)

**Comment by cydharrell** [comment]
Also, per conversation w/Frances Ho: let's change the link text to "When not to go to your county's court"

**Comment by jaredcwhite** [comment]
Fixed and pushed
