### ISSUE TITLE
Update Lorem ipsum text in Matters Served Explained pop-up

### ISSUE THREAD

**Issue by exygy-dev** [Exygy/ftrc#22]
As a user, I would like to be able to view definitions for various Matters Served so that I can understand what types of issues can be resolved at each court.

In each courthouse card, there will be a 'Matters Served' section, which includes hyperlinked text, reading 'What does this mean?' Clicking this link will open a pop-up window with definitions for each matter served.

Styling already been applied-- we just need to update the Lorem ipsum text here to the text in this document: https://docs.google.com/document/d/1yil1RAOo4qWhMxzPTsS7l65ghp85a5tkmdaE3z84mOY/edit

**Comment by jaredcwhite** [comment]
Fixed and pushed
