### ISSUE TITLE
Update CSS styling for row court-card

### ISSUE THREAD

**Issue by exygy-dev** [Exygy/ftrc#26]
Changes required (see image below):
---
- "Matters Served" text - bold & update font-color to #284868
- Remove italics on "Parking", "Transportation" and "Hours" and replace with bold
- Remove italics on hours text

Example
---
![image](https://user-images.githubusercontent.com/13025486/51780573-657ed300-20c4-11e9-83ca-6c68cda6cbdc.png)

**Comment by jaredcwhite** [comment]
Fixed and pushed.
