### ISSUE TITLE
Update Matter Served filter text and add "What does this mean" link

### ISSUE THREAD

**Issue by exygy-dev** [Exygy/ftrc#29]
Description
---
In the text above the drop-down filter, change from "Matter Served" to "Matters Served" and add "What does this mean" link.

See image
---
![image](https://user-images.githubusercontent.com/13025486/51780963-002ce100-20c8-11e9-8e6a-58ea60facdfc.png)

**Comment by jaredcwhite** [comment]
Fixed and pushed.
