### ISSUE TITLE
Add CSS styling for 'Select a county' intercept screen

### ISSUE THREAD

**Issue by exygy-dev** [Exygy/ftrc#32]
Changes
---
- Update "2 counties have..." text from P to H4
- Apply same styling as the top-alert container

Current
---
![image](https://user-images.githubusercontent.com/13025486/51781276-61a27f00-20cb-11e9-97ba-13d5efc3b149.png)

Target
---
![image](https://user-images.githubusercontent.com/13025486/51781428-4fc1db80-20cd-11e9-8ae9-55a7a658c099.png)

**Comment by jaredcwhite** [comment]
Fixed and closed.
