### ISSUE TITLE
shorten link copy from "What does this mean?" to "What's this?"

### ISSUE THREAD

**Issue by cydharrell** [Exygy/ftrc#34]
Probably because of the iFrame, on mobile the "What does this mean?" link that should be next to Matters Served wraps around so that it appears to be a header for the Matter dropdown. It's confusing. For a quick solution, let's shorten the text so it doesn't happen. Let's use "What's this?" instead.

![image](https://user-images.githubusercontent.com/5133498/52020455-2ecf0100-24a6-11e9-9739-ded27c554217.png)

**Comment by jaredcwhite** [comment]
Fixed and pushed.
