### ISSUE TITLE
headline language for jurisdictions with one courthouse

### ISSUE THREAD

**Issue by cydharrell** [Exygy/ftrc#9]
About 1/3 of our courts have one single courthouse. On their results pages, we return "There are 1 Courthouses Locations in this jurisdiction". Is it possible to change this for when it's a single result?

**Comment by exygy-dev** [comment]
@cydharrell Are we certain that all matters are handled at that courthouse? If not, we might want to hedge and use "There is 1 Courthouse location in this jurisdiction"

**Comment by cydharrell** [comment]
yes, all court matters where that Superior Court has jurisdiction will be handled at the one courthouse for single-courthouse counties. the best solution may be to remove that entire section - we don't need the dropdown or the self-help checkbox either. I'm open to design input, but this seems least confusing.

**Comment by jaredcwhite** [comment]
Fixed and pushed.
